### ISSUE TITLE
level 1 EventStub cannot be cast to class java.lang.Comparable

### ISSUE THREAD

**Issue by pearlynliu** [nus-cs2030/2122-s2#184] opened 2022-03-31 09:48 UTC
## Description 
Hi! When I run the test cases for level 1, this error appears.
![image](https://user-images.githubusercontent.com/80095533/161027111-91d3356f-84df-4dc2-b9cf-3265d81ebb62.png)

I am not sure if the problem is with my implementation of EventStub or PQ. I made EventStub implement Event and my constructor for PQ(cmp) makes use of `new PriorityQueue<T>(cmp)`. However, I think the error might be in my PQ add method.

This is what I did for my PQ add method.
![image](https://user-images.githubusercontent.com/80095533/161026287-ea351bee-f81e-449f-8756-236326cb3158.png)

may i get some advice on how to fix this? any help will be greatly appreciated!!

**Comment by Darien2307** [comment] 2022-03-31 09:55
Hi, my add method was initially the same as yours. In essence, if you refer to our ImList methods, the add in PQ is almost a duplicate of that in ImList. In this case, the first line of your PQ add method can be 
`PQ<T> newPQ = new PQ<T>(this.priorityqueue)`
`newPQ.pq.add(elem)`
and return the new PQ directly.
Hope I'm correct and hope it helps!

**Closed** 2022-03-31 15:23 UTC
Labels: :keyboard: Project
